name: deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - name: Install dependencies
      run: |
        flutter config --enable-web
        flutter pub get
    - name: Build
      run: |
        flutter build web
        touch build/web/.nojekyll
        echo 'fltkeep.xinthink.com' > build/web/CNAME
        echo "${{ secrets.FirebaseInitJs }}" | base64 --decode > build/web/init-firebase.js
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2.9.0
      env: FirebaseInitJs
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build/web
      with:
        emptyCommits: false
    - name: Notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.TelegramBotToken }}
        chatId: ${{ secrets.TelegramTarget }}
        jobStatus: ${{ job.status }}
